dist: trusty
addons:
  sonarqube:
    organization: "h-j-k-github"
language: java
before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- chmod +x ./gradlew
matrix:
  include:
    - env: JDK='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- ./gradlew jacocoTestReport sonarqube && bash <(curl -s https://codecov.io/bash)